### ISSUE TITLE
It doesn't work on Unity 5.3.3.

### ISSUE THREAD

**Issue by kimsama** [tsubaki/AnimatorLikeAnimatoin#1]
I know you've done with Unity 5.4 beta but it does not work on Unity 5.3.3.

**Comment by kimsama** [comment]
![error-5 4](https://cloud.githubusercontent.com/assets/564941/15564273/502db6ac-234b-11e6-8a66-54f2e7afb0da.png)

Even on Unity 5.4. the gameobject in the scene is missing. All scenes have same error as this.

**Comment by tsubaki** [comment]
Hi kimsama.

Unity 5.3 and 5.4 looks like the format of the serialization animation controller is different.
It can upgrade, but downgrade will not work.

I made 5.3 version.
Can you check it?
https://github.com/tsubaki/AnimatorLikeAnimatoin/tree/Unity5.3

**Comment by kimsama** [comment]
Thank you. The branch Unity5.3 definitely works fine.
